import type { Product } from '~/types'

// Стабільні Unsplash URL — товарні фото авто/детейлінг тематики
const img = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?w=${w}&q=80&auto=format&fit=crop`

export const products: Product[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. АВТОШАМПУНІ (8)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'p001',
    slug: 'turbofoam-active-1l',
    title: 'TurboFoam Active 1L — Активна піна',
    brand: 'ТурбоХім',
    category: 'shampoo',
    price: 349,
    oldPrice: 419,
    rating: 4.8,
    reviewsCount: 124,
    inStock: true,
    volume: '1 л',
    badges: ['hit', 'sale'],
    shortDescription: 'Концентрована активна піна для безконтактного миття. pH 12.',
    description:
      'Високолужний концентрат для безконтактного миття автомобіля. Ефективно видаляє дорожню грязь, комах, ґрунтові забруднення. Розбавлення 1:5 — 1:10 залежно від ступеня забруднення.',
    features: ['pH 12 (лужний)', 'Концентрат 1:5–1:10', 'Густа піна', 'Безпечний для ЛФП'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [
      img('photo-1605618826115-fb9e0c4d6a73'),
      img('photo-1607860108855-64acf2078ed9')
    ]
  },
  {
    id: 'p002',
    slug: 'snowfoam-premium-5l',
    title: 'SnowFoam Premium 5L',
    brand: 'DetailPro',
    category: 'shampoo',
    price: 1190,
    rating: 4.9,
    reviewsCount: 87,
    inStock: true,
    volume: '5 л',
    badges: ['hit'],
    shortDescription: 'Снігова піна з вишневим ароматом для пінокомплекту.',
    description:
      'Преміальна снігова піна з густою текстурою та тривалим часом контакту. Розчиняє органічні забруднення без шкоди для воску та керамічних покриттів.',
    features: ['pH 7.5 (нейтральний)', 'Густа піна', 'Аромат вишні', 'Безпечний для кераміки'],
    image: img('photo-1607860108855-64acf2078ed9'),
    gallery: [img('photo-1607860108855-64acf2078ed9')]
  },
  {
    id: 'p003',
    slug: 'hand-wash-shampoo-500ml',
    title: 'HandWash Shampoo 500ml',
    brand: 'ТурбоХім',
    category: 'shampoo',
    price: 219,
    rating: 4.6,
    reviewsCount: 56,
    inStock: true,
    volume: '500 мл',
    badges: ['new'],
    shortDescription: 'pH-нейтральний шампунь для ручного миття.',
    description:
      'Класичний шампунь для ручного миття з рукавицею. Густа стійка піна, легке полоскання, аромат свіжості.',
    features: ['pH 7', 'Концентрат 1:200', 'Без розводів', '500 мл'],
    image: img('photo-1601362840469-51e4d8d58785'),
    gallery: [img('photo-1601362840469-51e4d8d58785')]
  },
  {
    id: 'p004',
    slug: 'wax-shampoo-1l',
    title: 'Wax Shampoo 1L — шампунь з воском',
    brand: 'WaxLine',
    category: 'shampoo',
    price: 459,
    oldPrice: 539,
    rating: 4.7,
    reviewsCount: 73,
    inStock: true,
    volume: '1 л',
    badges: ['sale'],
    shortDescription: 'Шампунь з карнаубським воском — миття + захист.',
    description:
      'Шампунь 2-в-1 із додаванням карнаубського воску. Залишає водовідштовхувальний шар після кожного миття.',
    features: ['Із карнаубою', 'Гідрофоб ~1 тиждень', 'Глянцевий ефект'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p005',
    slug: 'truck-foam-5l',
    title: 'TruckFoam 5L — для вантажівок',
    brand: 'HeavyClean',
    category: 'shampoo',
    price: 1390,
    rating: 4.5,
    reviewsCount: 31,
    inStock: true,
    volume: '5 л',
    badges: [],
    shortDescription: 'Сильна лужна піна для вантажного транспорту.',
    description:
      'Спеціалізований склад для миття вантажівок, спецтехніки та сильно забруднених поверхонь. Розбавлення до 1:15.',
    features: ['pH 13', 'Для вантажівок', 'Розчиняє масло та сажу'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },
  {
    id: 'p006',
    slug: 'eco-shampoo-1l',
    title: 'Eco Shampoo 1L — біорозкладний',
    brand: 'GreenCare',
    category: 'shampoo',
    price: 389,
    rating: 4.8,
    reviewsCount: 42,
    inStock: true,
    volume: '1 л',
    badges: ['new'],
    shortDescription: 'Біорозкладний шампунь на рослинній основі.',
    description:
      'Екологічний шампунь без фосфатів та агресивних ПАР. Розкладається в природі за 28 днів. Сертифікат EcoLabel.',
    features: ['Біорозкладний', 'Без фосфатів', 'EcoLabel', 'Гіпоалергенний'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [img('photo-1605618826115-fb9e0c4d6a73')]
  },
  {
    id: 'p007',
    slug: 'shampoo-concentrate-10l',
    title: 'Shampoo Concentrate 10L',
    brand: 'DetailPro',
    category: 'shampoo',
    price: 2390,
    rating: 4.9,
    reviewsCount: 19,
    inStock: false,
    volume: '10 л',
    badges: [],
    shortDescription: 'Професійна каністра для автомийок.',
    description:
      'Об\'ємна упаковка для автомийок самообслуговування та детейлінг-студій. Економний концентрат.',
    features: ['10 л', 'Для автомийок', 'Економія до 40%'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p008',
    slug: 'rinseless-wash-500ml',
    title: 'Rinseless Wash 500ml — миття без води',
    brand: 'ТурбоХім',
    category: 'shampoo',
    price: 549,
    rating: 4.6,
    reviewsCount: 38,
    inStock: true,
    volume: '500 мл',
    badges: ['new'],
    shortDescription: 'Технологія миття без змивання водою.',
    description:
      'Інкапсулюючий склад для миття без води. Підходить для квартир без доступу до мийки.',
    features: ['Без води', 'Інкапсуляція бруду', 'Гідрофобний ефект'],
    image: img('photo-1542362567-b07e54358753'),
    gallery: [img('photo-1542362567-b07e54358753')]
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. ПОЛІРОЛІ (8)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'p101',
    slug: 'cut-polish-pro-500ml',
    title: 'Cut Polish PRO 500ml — абразивна',
    brand: 'DetailPro',
    category: 'polish',
    price: 890,
    oldPrice: 1090,
    rating: 4.9,
    reviewsCount: 64,
    inStock: true,
    volume: '500 мл',
    badges: ['hit', 'sale'],
    shortDescription: 'Абразивна паста для усунення глибоких подряпин.',
    description:
      'Тверда абразивна паста з різальною здатністю до 1500 grit. Видаляє голограми, подряпини та сліди голок щіток автомийок.',
    features: ['Cut 8/10', 'Gloss 6/10', 'Без силікону', 'Body shop safe'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p102',
    slug: 'finish-polish-300ml',
    title: 'Finish Polish 300ml — фінішна',
    brand: 'DetailPro',
    category: 'polish',
    price: 690,
    rating: 4.8,
    reviewsCount: 51,
    inStock: true,
    volume: '300 мл',
    badges: ['hit'],
    shortDescription: 'Фінішна паста для глибокого глянцю.',
    description:
      'Зменшує голограми, додає дзеркальний блиск. Працює з м\'якими поролоновими колами.',
    features: ['Cut 2/10', 'Gloss 10/10', 'Антиголограма'],
    image: img('photo-1607860108855-64acf2078ed9'),
    gallery: [img('photo-1607860108855-64acf2078ed9')]
  },
  {
    id: 'p103',
    slug: 'one-step-polish-500ml',
    title: 'One-Step Polish 500ml',
    brand: 'ТурбоХім',
    category: 'polish',
    price: 549,
    rating: 4.7,
    reviewsCount: 89,
    inStock: true,
    volume: '500 мл',
    badges: [],
    shortDescription: 'Універсальна паста — все за одну операцію.',
    description:
      'Поєднує абразив та фінішну поліроль. Ідеально для DIY-користувачів та швидкого освіження ЛФП.',
    features: ['Cut 5/10', 'Gloss 8/10', '1-step', 'DIY-friendly'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [img('photo-1605618826115-fb9e0c4d6a73')]
  },
  {
    id: 'p104',
    slug: 'liquid-wax-500ml',
    title: 'Liquid Wax 500ml — рідкий віск',
    brand: 'WaxLine',
    category: 'polish',
    price: 459,
    rating: 4.6,
    reviewsCount: 73,
    inStock: true,
    volume: '500 мл',
    badges: ['new'],
    shortDescription: 'Рідкий віск з карнаубою на 3 місяці.',
    description:
      'Захисний рідкий віск після полірування. Гідрофобний ефект, легке нанесення мікрофіброю.',
    features: ['3 місяці захисту', 'Карнауба 30%', 'Легке нанесення'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p105',
    slug: 'headlight-polish-kit',
    title: 'Headlight Polish Kit — для фар',
    brand: 'ТурбоХім',
    category: 'polish',
    price: 749,
    oldPrice: 899,
    rating: 4.8,
    reviewsCount: 122,
    inStock: true,
    badges: ['hit', 'sale'],
    shortDescription: 'Набір для відновлення помутнілих фар.',
    description:
      'Комплект включає абразиви 1000/2000/3000 grit, пасту, захисний лак UV. Повне відновлення прозорості.',
    features: ['Абразиви 1000–3000', 'UV-лак', 'Інструкція'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },
  {
    id: 'p106',
    slug: 'plastic-restorer-250ml',
    title: 'Plastic Restorer 250ml',
    brand: 'DetailPro',
    category: 'polish',
    price: 389,
    rating: 4.5,
    reviewsCount: 47,
    inStock: true,
    volume: '250 мл',
    badges: [],
    shortDescription: 'Відновлювач чорного пластику зовні.',
    description:
      'Повертає глибокий чорний колір зовнішньому пластику (бампери, молдінги). Захист до 6 місяців.',
    features: ['6 місяців ефекту', 'Не липкий', 'УФ-стійкий'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p107',
    slug: 'compound-polish-1l',
    title: 'Compound Polish 1L — професійна',
    brand: 'ProDetail',
    category: 'polish',
    price: 1290,
    rating: 4.9,
    reviewsCount: 28,
    inStock: true,
    volume: '1 л',
    badges: [],
    shortDescription: 'Професійна абразивна паста для детейлерів.',
    description:
      'Об\'ємна упаковка для студій. Працює з машинками DA та ротаційними. Сумісна з усіма типами поролону.',
    features: ['1 л', 'DA + Rotary', 'Body shop safe'],
    image: img('photo-1607860108855-64acf2078ed9'),
    gallery: [img('photo-1607860108855-64acf2078ed9')]
  },
  {
    id: 'p108',
    slug: 'glass-polish-200ml',
    title: 'Glass Polish 200ml — для скла',
    brand: 'ТурбоХім',
    category: 'polish',
    price: 329,
    rating: 4.7,
    reviewsCount: 65,
    inStock: true,
    volume: '200 мл',
    badges: ['new'],
    shortDescription: 'Церій-оксидна паста для скла.',
    description:
      'Видаляє водні плями, дрібні подряпини зі скла. На основі оксиду церію.',
    features: ['Cerium Oxide', 'Для скла', 'Видаляє watermarks'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. ОЧИЩУВАЧІ САЛОНУ (8)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'p201',
    slug: 'interior-cleaner-1l',
    title: 'Interior Cleaner 1L — універсальний',
    brand: 'ТурбоХім',
    category: 'interior',
    price: 359,
    rating: 4.8,
    reviewsCount: 156,
    inStock: true,
    volume: '1 л',
    badges: ['hit'],
    shortDescription: 'Універсальний APC для всіх поверхонь салону.',
    description:
      'All Purpose Cleaner — пластик, текстиль, шкіра, оббивка стелі. Розбавляється 1:4 для м\'яких поверхонь.',
    features: ['Універсальний', 'Розбавляється 1:1–1:10', 'Не залишає розводів'],
    image: img('photo-1542362567-b07e54358753'),
    gallery: [img('photo-1542362567-b07e54358753')]
  },
  {
    id: 'p202',
    slug: 'leather-cleaner-500ml',
    title: 'Leather Cleaner 500ml',
    brand: 'LeatherCare',
    category: 'interior',
    price: 549,
    oldPrice: 649,
    rating: 4.9,
    reviewsCount: 89,
    inStock: true,
    volume: '500 мл',
    badges: ['hit', 'sale'],
    shortDescription: 'Очищувач шкіряних сидінь, pH-нейтральний.',
    description:
      'М\'який очищувач для шкіри з pH 5.5. Видаляє пігменти від джинсів, забруднення, не сушить шкіру.',
    features: ['pH 5.5', 'Безпечний для шкіри', 'Видаляє денім-трансфер'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [img('photo-1605618826115-fb9e0c4d6a73')]
  },
  {
    id: 'p203',
    slug: 'leather-conditioner-250ml',
    title: 'Leather Conditioner 250ml',
    brand: 'LeatherCare',
    category: 'interior',
    price: 489,
    rating: 4.8,
    reviewsCount: 67,
    inStock: true,
    volume: '250 мл',
    badges: [],
    shortDescription: 'Кондиціонер для шкіри з UV-захистом.',
    description:
      'Живить, зволожує та захищає шкіру від УФ. Матовий фініш без липкості.',
    features: ['UV-захист', 'Матовий фініш', 'Не липкий'],
    image: img('photo-1542362567-b07e54358753'),
    gallery: [img('photo-1542362567-b07e54358753')]
  },
  {
    id: 'p204',
    slug: 'textile-cleaner-1l',
    title: 'Textile Cleaner 1L — для тканини',
    brand: 'ТурбоХім',
    category: 'interior',
    price: 429,
    rating: 4.7,
    reviewsCount: 94,
    inStock: true,
    volume: '1 л',
    badges: ['new'],
    shortDescription: 'Активний очищувач тканинних сидінь та оббивки стелі.',
    description:
      'Видаляє кавові плями, жир, сліди від їжі. Антибактеріальна формула, не залишає розводів.',
    features: ['Антибактеріальний', 'Без розводів', 'Для оббивки стелі'],
    image: img('photo-1601362840469-51e4d8d58785'),
    gallery: [img('photo-1601362840469-51e4d8d58785')]
  },
  {
    id: 'p205',
    slug: 'plastic-dressing-500ml',
    title: 'Plastic Dressing 500ml — для пластику',
    brand: 'DetailPro',
    category: 'interior',
    price: 379,
    rating: 4.6,
    reviewsCount: 73,
    inStock: true,
    volume: '500 мл',
    badges: [],
    shortDescription: 'Поліроль для внутрішнього пластику, матовий фініш.',
    description:
      'Освіжає торпеду, дверні карти, центральну консоль. Матовий ефект, антистатик.',
    features: ['Матовий', 'Антистатик', 'УФ-захист'],
    image: img('photo-1542362567-b07e54358753'),
    gallery: [img('photo-1542362567-b07e54358753')]
  },
  {
    id: 'p206',
    slug: 'glass-cleaner-500ml',
    title: 'Glass Cleaner 500ml — для скла',
    brand: 'ТурбоХім',
    category: 'interior',
    price: 219,
    rating: 4.8,
    reviewsCount: 187,
    inStock: true,
    volume: '500 мл',
    badges: ['hit'],
    shortDescription: 'Без аміаку, без розводів — для скла та дзеркал.',
    description:
      'Засіб для миття скла без аміаку. Безпечний для тонувальних плівок та екранів медіасистем.',
    features: ['Без аміаку', 'Безпечний для тонування', 'Антистатик'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p207',
    slug: 'odor-eliminator-250ml',
    title: 'Odor Eliminator 250ml',
    brand: 'FreshAir',
    category: 'interior',
    price: 459,
    rating: 4.7,
    reviewsCount: 102,
    inStock: true,
    volume: '250 мл',
    badges: ['new'],
    shortDescription: 'Нейтралізатор запахів (тютюн, тварини).',
    description:
      'Не маскує, а молекулярно нейтралізує запахи. Працює з тютюновим димом, шерстю, їжею.',
    features: ['Молекулярна нейтралізація', 'Без ароматизаторів', 'Гіпоалергенний'],
    image: img('photo-1542362567-b07e54358753'),
    gallery: [img('photo-1542362567-b07e54358753')]
  },
  {
    id: 'p208',
    slug: 'air-conditioner-cleaner',
    title: 'AC Cleaner — очищувач кондиціонера',
    brand: 'ТурбоХім',
    category: 'interior',
    price: 329,
    oldPrice: 399,
    rating: 4.6,
    reviewsCount: 78,
    inStock: true,
    volume: '300 мл аерозоль',
    badges: ['sale'],
    shortDescription: 'Антибактеріальний очищувач випарника AC.',
    description:
      'Аерозоль для дезінфекції випарника та системи кондиціонування. Усуває запах сирості та пліснявил.',
    features: ['Антибактеріальний', 'Аерозоль', 'Для випарника'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. ЗАСОБИ ДЛЯ ДИСКІВ (7)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'p301',
    slug: 'wheel-cleaner-1l',
    title: 'Wheel Cleaner 1L — лужний',
    brand: 'ТурбоХім',
    category: 'wheels',
    price: 429,
    rating: 4.8,
    reviewsCount: 134,
    inStock: true,
    volume: '1 л',
    badges: ['hit'],
    shortDescription: 'Лужний очищувач для будь-яких типів дисків.',
    description:
      'Видаляє гальмівний пил, дорожню грязь, бітум. Безпечний для фарбованих, поліровних та хромованих дисків.',
    features: ['pH 11.5', 'Для всіх дисків', 'Розчиняє гальмівний пил'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p302',
    slug: 'iron-out-500ml',
    title: 'Iron Out 500ml — індикатор іржі',
    brand: 'DetailPro',
    category: 'wheels',
    price: 749,
    oldPrice: 899,
    rating: 4.9,
    reviewsCount: 156,
    inStock: true,
    volume: '500 мл',
    badges: ['hit', 'sale'],
    shortDescription: 'Хімічний декомтамінант — змінює колір на фіолетовий.',
    description:
      'Реагує з частинками металу (брейк-даст, металева пилюка). Поверхня стає фіолетовою — ефект "плачу залозом".',
    features: ['Колірна індикація', 'pH-нейтральний', 'Для ЛФП і дисків'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p303',
    slug: 'acid-wheel-cleaner-1l',
    title: 'Acid Wheel Cleaner 1L',
    brand: 'HeavyClean',
    category: 'wheels',
    price: 589,
    rating: 4.5,
    reviewsCount: 41,
    inStock: true,
    volume: '1 л',
    badges: [],
    shortDescription: 'Кислотний очищувач для важких забруднень.',
    description:
      'Сильний кислотний склад для запущених дисків. УВАГА: не для поліровних та хромованих коліс.',
    features: ['pH 1.5', 'Сильна дія', 'Тільки для фарбованих дисків'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p304',
    slug: 'tire-shine-500ml',
    title: 'Tire Shine 500ml — чорнитель шин',
    brand: 'ТурбоХім',
    category: 'wheels',
    price: 319,
    rating: 4.7,
    reviewsCount: 198,
    inStock: true,
    volume: '500 мл',
    badges: ['hit'],
    shortDescription: 'Глянцевий чорнитель шин на водній основі.',
    description:
      'Не розбризкується під час руху, не липкий. Тримається 2–3 миття. Глянцевий або матовий ефект на вибір.',
    features: ['Водна основа', '2–3 миття', 'Не розбризкується'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },
  {
    id: 'p305',
    slug: 'tire-shine-matte-500ml',
    title: 'Tire Shine Matte 500ml',
    brand: 'DetailPro',
    category: 'wheels',
    price: 389,
    rating: 4.6,
    reviewsCount: 87,
    inStock: true,
    volume: '500 мл',
    badges: ['new'],
    shortDescription: 'Матовий чорнитель — заводський look.',
    description:
      'Матовий фініш — як з нових шин. Сатиновий ефект, тримається до 4 тижнів.',
    features: ['Матовий', '4 тижні', 'Заводський look'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p306',
    slug: 'wheel-sealant-100ml',
    title: 'Wheel Sealant 100ml — захист дисків',
    brand: 'CeramicPro',
    category: 'wheels',
    price: 1290,
    rating: 4.9,
    reviewsCount: 43,
    inStock: true,
    volume: '100 мл',
    badges: ['new'],
    shortDescription: 'Керамічний герметик для дисків на 12 місяців.',
    description:
      'Захищає диски від гальмівного пилу та хімії. Полегшує миття — забруднення не прилипають.',
    features: ['12 місяців', 'Захист від хімії', 'Anti-stick'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [img('photo-1605618826115-fb9e0c4d6a73')]
  },
  {
    id: 'p307',
    slug: 'brake-cleaner-500ml',
    title: 'Brake Cleaner 500ml',
    brand: 'ТурбоХім',
    category: 'wheels',
    price: 259,
    rating: 4.7,
    reviewsCount: 112,
    inStock: true,
    volume: '500 мл',
    badges: [],
    shortDescription: 'Очищувач гальмівних супортів і дисків.',
    description:
      'Знежирює гальмівні поверхні перед обслуговуванням. Випаровується без залишків.',
    features: ['Знежирювач', 'Без залишків', 'Для механіки'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. ЗАХИСНІ ПОКРИТТЯ (8)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'p401',
    slug: 'ceramic-9h-30ml',
    title: 'Ceramic 9H 30ml — керамічне покриття',
    brand: 'CeramicPro',
    category: 'protection',
    price: 2890,
    oldPrice: 3290,
    rating: 4.9,
    reviewsCount: 78,
    inStock: true,
    volume: '30 мл',
    badges: ['hit', 'sale'],
    shortDescription: 'Професійна кераміка 9H на 24 місяці.',
    description:
      'Тверде керамічне покриття 9H. Гідрофобний ефект, стійкість до подряпин, УФ та хімії.',
    features: ['9H твердість', '24 місяці', 'Гідрофобний', 'Anti-scratch'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p402',
    slug: 'graphene-coating-50ml',
    title: 'Graphene Coating 50ml',
    brand: 'GrapheneShield',
    category: 'protection',
    price: 3490,
    rating: 5.0,
    reviewsCount: 32,
    inStock: true,
    volume: '50 мл',
    badges: ['new'],
    shortDescription: 'Графенове покриття на 5 років.',
    description:
      'Інноваційне графенове покриття. Краща термостійкість і гідрофобність порівняно з керамікою.',
    features: ['5 років', 'Термостійкість', 'Графен'],
    image: img('photo-1607860108855-64acf2078ed9'),
    gallery: [img('photo-1607860108855-64acf2078ed9')]
  },
  {
    id: 'p403',
    slug: 'spray-sealant-500ml',
    title: 'Spray Sealant 500ml',
    brand: 'ТурбоХім',
    category: 'protection',
    price: 749,
    rating: 4.7,
    reviewsCount: 145,
    inStock: true,
    volume: '500 мл',
    badges: ['hit'],
    shortDescription: 'Швидкий гідрофобний спрей після миття.',
    description:
      'Наноситься на мокре авто. Гідрофобний ефект 2–3 місяці. Підсилює існуючу кераміку.',
    features: ['2–3 місяці', 'Topper для кераміки', 'На мокре авто'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [img('photo-1605618826115-fb9e0c4d6a73')]
  },
  {
    id: 'p404',
    slug: 'carnauba-wax-200g',
    title: 'Carnauba Wax 200g — твердий віск',
    brand: 'WaxLine',
    category: 'protection',
    price: 1290,
    oldPrice: 1490,
    rating: 4.9,
    reviewsCount: 67,
    inStock: true,
    volume: '200 г',
    badges: ['sale'],
    shortDescription: 'Твердий віск з 50% карнауби.',
    description:
      'Класичний твердий віск для глибокого глянцю. Карнауба бразильська, T1 grade. 3–4 місяці захисту.',
    features: ['50% карнауба', 'T1 grade', '3–4 місяці'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p405',
    slug: 'glass-coating-30ml',
    title: 'Glass Coating 30ml — антидощ',
    brand: 'CeramicPro',
    category: 'protection',
    price: 549,
    rating: 4.8,
    reviewsCount: 234,
    inStock: true,
    volume: '30 мл',
    badges: ['hit'],
    shortDescription: 'Гідрофобне покриття для лобового скла.',
    description:
      'Краплі скочуються при швидкості від 60 км/год. Покращує видимість у дощ, тримається 6 місяців.',
    features: ['6 місяців', 'Від 60 км/год', 'Покращує видимість'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p406',
    slug: 'plastic-coating-100ml',
    title: 'Plastic Coating 100ml',
    brand: 'DetailPro',
    category: 'protection',
    price: 689,
    rating: 4.7,
    reviewsCount: 56,
    inStock: true,
    volume: '100 мл',
    badges: ['new'],
    shortDescription: 'Захист зовнішнього пластику від вигорання.',
    description:
      'Захищає бампери та молдінги від УФ. Глибокий чорний колір на 12 місяців.',
    features: ['12 місяців', 'UV-захист', 'Для пластику'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p407',
    slug: 'leather-coating-50ml',
    title: 'Leather Coating 50ml',
    brand: 'LeatherCare',
    category: 'protection',
    price: 989,
    rating: 4.8,
    reviewsCount: 41,
    inStock: false,
    volume: '50 мл',
    badges: [],
    shortDescription: 'Захисне покриття для шкіри салону.',
    description:
      'Запобігає протиранню та фарбуванню шкіри від джинсів. Тримається 12 місяців.',
    features: ['12 місяців', 'Anti-dye transfer', 'Невидиме'],
    image: img('photo-1542362567-b07e54358753'),
    gallery: [img('photo-1542362567-b07e54358753')]
  },
  {
    id: 'p408',
    slug: 'fabric-protector-500ml',
    title: 'Fabric Protector 500ml',
    brand: 'ТурбоХім',
    category: 'protection',
    price: 489,
    rating: 4.6,
    reviewsCount: 89,
    inStock: true,
    volume: '500 мл',
    badges: [],
    shortDescription: 'Захист тканинних сидінь від рідин.',
    description:
      'Рідини скочуються, не проникаючи у тканину. Захист від кави, червоного вина, олії.',
    features: ['Water-repellent', 'Oil-repellent', 'Невидимий'],
    image: img('photo-1601362840469-51e4d8d58785'),
    gallery: [img('photo-1601362840469-51e4d8d58785')]
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. ХІМІЯ ДЛЯ ДВИГУНА (8)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'p501',
    slug: 'engine-degreaser-1l',
    title: 'Engine Degreaser 1L',
    brand: 'ТурбоХім',
    category: 'engine',
    price: 459,
    rating: 4.7,
    reviewsCount: 167,
    inStock: true,
    volume: '1 л',
    badges: ['hit'],
    shortDescription: 'Знежирювач для зовнішнього миття двигуна.',
    description:
      'Видаляє масляні нальоти, пил, мастило з підкапотного простору. Безпечний для пластику та електроніки.',
    features: ['pH 12', 'Безпечний для пластику', 'Концентрат 1:5'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },
  {
    id: 'p502',
    slug: 'engine-dressing-500ml',
    title: 'Engine Dressing 500ml — поліроль двигуна',
    brand: 'DetailPro',
    category: 'engine',
    price: 389,
    oldPrice: 459,
    rating: 4.8,
    reviewsCount: 124,
    inStock: true,
    volume: '500 мл',
    badges: ['sale'],
    shortDescription: 'Захисний спрей після миття двигуна.',
    description:
      'Освіжає пластикові деталі під капотом. Захищає від пилу, антистатик.',
    features: ['Антистатик', 'Захищає пластик', 'Не липкий'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },
  {
    id: 'p503',
    slug: 'oil-flush-300ml',
    title: 'Oil Flush 300ml — промивка масляної',
    brand: 'MotorClean',
    category: 'engine',
    price: 289,
    rating: 4.6,
    reviewsCount: 198,
    inStock: true,
    volume: '300 мл',
    badges: ['hit'],
    shortDescription: '5-хвилинна промивка масляної системи.',
    description:
      'Додається в старе масло за 5 хв до зливу. Розчиняє відкладення, очищує гідрокомпенсатори.',
    features: ['5 хвилин', 'Для всіх двигунів', 'Розчиняє нагар'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [img('photo-1605618826115-fb9e0c4d6a73')]
  },
  {
    id: 'p504',
    slug: 'decarbonizer-spray-400ml',
    title: 'Decarbonizer Spray 400ml',
    brand: 'MotorClean',
    category: 'engine',
    price: 549,
    rating: 4.7,
    reviewsCount: 87,
    inStock: true,
    volume: '400 мл',
    badges: ['new'],
    shortDescription: 'Розкоксовка впускної системи.',
    description:
      'Аерозоль для чистки EGR, дросельної заслінки, впускного колектора. Видаляє нагар і смоли.',
    features: ['Аерозоль', 'Для EGR/дроселя', 'Розчиняє нагар'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },
  {
    id: 'p505',
    slug: 'fuel-system-cleaner-300ml',
    title: 'Fuel System Cleaner 300ml',
    brand: 'ТурбоХім',
    category: 'engine',
    price: 219,
    rating: 4.6,
    reviewsCount: 234,
    inStock: true,
    volume: '300 мл',
    badges: ['hit'],
    shortDescription: 'Очисник паливної системи в бак.',
    description:
      'Очищує форсунки, клапани, камеру згоряння. Покращує запуск, знижує витрату пального.',
    features: ['У бак', 'Для бензину/дизеля', 'Знижує витрату'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p506',
    slug: 'radiator-flush-500ml',
    title: 'Radiator Flush 500ml',
    brand: 'MotorClean',
    category: 'engine',
    price: 329,
    rating: 4.5,
    reviewsCount: 76,
    inStock: true,
    volume: '500 мл',
    badges: [],
    shortDescription: 'Промивка системи охолодження.',
    description:
      'Видаляє накип, іржу, відкладення з радіатора та сорочки охолодження. Перед заміною антифризу.',
    features: ['Видаляє накип', 'Антикорозійний', 'Перед заміною'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },
  {
    id: 'p507',
    slug: 'diesel-additive-300ml',
    title: 'Diesel Additive 300ml',
    brand: 'ТурбоХім',
    category: 'engine',
    price: 259,
    rating: 4.7,
    reviewsCount: 145,
    inStock: true,
    volume: '300 мл',
    badges: [],
    shortDescription: 'Присадка для дизельного пального.',
    description:
      'Підвищує цетанове число, очищує форсунки, антибактеріальний ефект для бака.',
    features: ['Цетан +5', 'Антибактеріальний', 'Для дизеля'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [img('photo-1605618826115-fb9e0c4d6a73')]
  },
  {
    id: 'p508',
    slug: 'turbo-cleaner-400ml',
    title: 'Turbo Cleaner 400ml',
    brand: 'MotorClean',
    category: 'engine',
    price: 489,
    rating: 4.8,
    reviewsCount: 52,
    inStock: true,
    volume: '400 мл',
    badges: ['new'],
    shortDescription: 'Очищувач турбіни без розбирання.',
    description:
      'Розчиняє нагар на крильчатках турбіни. Безпечне застосування без знімання турбіни.',
    features: ['Без розбирання', 'Для турбіни', 'Видаляє нагар'],
    image: img('photo-1486262715619-67b85e0b08d3'),
    gallery: [img('photo-1486262715619-67b85e0b08d3')]
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. АКСЕСУАРИ (9)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'p601',
    slug: 'microfiber-towel-set-5',
    title: 'Мікрофібра 40×40 (5 шт)',
    brand: 'ТурбоХім',
    category: 'accessories',
    price: 289,
    oldPrice: 349,
    rating: 4.9,
    reviewsCount: 312,
    inStock: true,
    badges: ['hit', 'sale'],
    shortDescription: 'Набір мікрофібри 380 GSM, 40×40 см.',
    description:
      'Преміальна корейська мікрофібра 380 г/м². Без етикеток, оверлок-кант. Універсальна для салону та кузова.',
    features: ['380 GSM', '40×40 см', '5 штук', 'Корея'],
    image: img('photo-1601362840469-51e4d8d58785'),
    gallery: [img('photo-1601362840469-51e4d8d58785')]
  },
  {
    id: 'p602',
    slug: 'microfiber-drying-towel',
    title: 'Сушильна мікрофібра 60×90',
    brand: 'DetailPro',
    category: 'accessories',
    price: 549,
    rating: 4.9,
    reviewsCount: 156,
    inStock: true,
    badges: ['hit'],
    shortDescription: 'Twisted-loop 1100 GSM для сушки кузова.',
    description:
      'Велика twisted-loop мікрофібра для безпечної сушки після миття. Вбирає до 2 літрів води.',
    features: ['1100 GSM', '60×90 см', 'Twisted-loop', '2 л'],
    image: img('photo-1605618826115-fb9e0c4d6a73'),
    gallery: [img('photo-1605618826115-fb9e0c4d6a73')]
  },
  {
    id: 'p603',
    slug: 'wash-mitt-microfiber',
    title: 'MF-рукавиця для миття',
    brand: 'ТурбоХім',
    category: 'accessories',
    price: 219,
    rating: 4.8,
    reviewsCount: 198,
    inStock: true,
    badges: [],
    shortDescription: 'М\'яка рукавиця з густого ворсу.',
    description:
      'Густий ворс безпечно знімає бруд з кузова без подряпин. Внутрішня кишеня з гумкою.',
    features: ['Густий ворс', 'З кишенею', 'Машинне прання'],
    image: img('photo-1601362840469-51e4d8d58785'),
    gallery: [img('photo-1601362840469-51e4d8d58785')]
  },
  {
    id: 'p604',
    slug: 'grit-guard-bucket-kit',
    title: 'Відро 20л + Grit Guard',
    brand: 'DetailPro',
    category: 'accessories',
    price: 689,
    rating: 4.9,
    reviewsCount: 89,
    inStock: true,
    badges: ['hit'],
    shortDescription: 'Detail-відро 20 л з решіткою Grit Guard.',
    description:
      'Чорне 20-літрове відро з калібровкою. Решітка затримує бруд на дні — рукавиця не торкається його.',
    features: ['20 л', 'Grit Guard', 'Калібровка'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p605',
    slug: 'foam-applicator-set',
    title: 'Аплікатори поролонові (6 шт)',
    brand: 'ТурбоХім',
    category: 'accessories',
    price: 129,
    rating: 4.7,
    reviewsCount: 167,
    inStock: true,
    badges: [],
    shortDescription: 'Поролонові аплікатори для воску та покриттів.',
    description:
      'Набір 6 круглих аплікаторів. Не вбирають продукт надмірно, рівномірне нанесення.',
    features: ['6 штук', 'Поролон', 'Багаторазові'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p606',
    slug: 'wheel-brush-soft',
    title: 'Щітка для дисків — м\'яка',
    brand: 'DetailPro',
    category: 'accessories',
    price: 329,
    rating: 4.8,
    reviewsCount: 124,
    inStock: true,
    badges: ['new'],
    shortDescription: 'Wheel woolie з овечої вовни 45 см.',
    description:
      'Довга м\'яка щітка з овечої вовни для миття внутрішньої поверхні дисків. Не дряпає.',
    features: ['Овеча вовна', '45 см', 'Не дряпає'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  },
  {
    id: 'p607',
    slug: 'detail-brush-set-5',
    title: 'Детейлінг-щітки (5 шт)',
    brand: 'ТурбоХім',
    category: 'accessories',
    price: 219,
    rating: 4.7,
    reviewsCount: 145,
    inStock: true,
    badges: [],
    shortDescription: 'Набір щіток для салону та екстер\'єру.',
    description:
      'Боржун різного розміру: для дефлекторів, дверних ручок, решіток, швів. М\'який ворс.',
    features: ['5 щіток', 'М\'який ворс', 'Для салону+кузова'],
    image: img('photo-1601362840469-51e4d8d58785'),
    gallery: [img('photo-1601362840469-51e4d8d58785')]
  },
  {
    id: 'p608',
    slug: 'clay-bar-200g',
    title: 'Clay Bar 200g — глина для кузова',
    brand: 'DetailPro',
    category: 'accessories',
    price: 359,
    rating: 4.8,
    reviewsCount: 187,
    inStock: true,
    badges: [],
    shortDescription: 'Глина середньої абразивності — 200 г.',
    description:
      'Видаляє в\'їдені забруднення (бітум, метал, ґрунт). Використовується з мастилом-лубрикантом.',
    features: ['200 г', 'Medium grade', 'Перед покриттям'],
    image: img('photo-1492144534655-ae79c964c9d7'),
    gallery: [img('photo-1492144534655-ae79c964c9d7')]
  },
  {
    id: 'p609',
    slug: 'spray-bottle-pro-1l',
    title: 'Пляшка-розпилювач PRO 1 л',
    brand: 'ТурбоХім',
    category: 'accessories',
    price: 159,
    rating: 4.6,
    reviewsCount: 234,
    inStock: true,
    badges: ['new'],
    shortDescription: 'Хімостійка пляшка з тригером.',
    description:
      'Витривалий тригер на 50 000 натискань. Хімостійка пляшка для роздачі концентратів.',
    features: ['Хімостійка', '50 000 циклів', '1 л'],
    image: img('photo-1611162616305-c69b3fa7fbe0'),
    gallery: [img('photo-1611162616305-c69b3fa7fbe0')]
  }
]
